<#
.SYNOPSIS
  AZCopy GUI for PST Import

.DESCRIPTION
  A simple GUI wrapper for AZCopy.exe to simplify the process of importing .PSTs into Exchange Online

.INPUTS
  None

.OUTPUTS
  None

.NOTES
  Version:        1.1
  Author:         Chris Goosen (Twitter: @chrisgoosen)
  Creation Date:  07/23/2015
.LINK
  http://www.cgoosen.com

.EXAMPLE
  .\Get-AZCopyGUI.ps1
#>
$ErrorActionPreference = "Stop"
# GUI Form
function Call-GUI {
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
$form = New-Object System.Windows.Forms.Form
$CancelButton = New-Object System.Windows.Forms.Button
$OkButton = New-Object System.Windows.Forms.Button
$groupBox1 = New-Object System.Windows.Forms.GroupBox
$checkBox2 = New-Object System.Windows.Forms.CheckBox
$checkBox1 = New-Object System.Windows.Forms.CheckBox
$checkBox3 = New-Object System.Windows.Forms.CheckBox
$label5 = New-Object System.Windows.Forms.Label
$button4 = New-Object System.Windows.Forms.Button
$textBox4 = New-Object System.Windows.Forms.TextBox
$label3 = New-Object System.Windows.Forms.Label
$label4 = New-Object System.Windows.Forms.Label
$textBox3 = New-Object System.Windows.Forms.TextBox
$label2 = New-Object System.Windows.Forms.Label
$textBox2 = New-Object System.Windows.Forms.TextBox
$BrowseButton = New-Object System.Windows.Forms.Button
$textBox1 = New-Object System.Windows.Forms.TextBox
$label1 = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
$menu = New-Object 'System.Windows.Forms.MenuStrip'
$fileToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$exitToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$editToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$copyToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$pasteToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$helpToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$versionMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$helpMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
$form_FormClosing = [System.Windows.Forms.FormClosingEventHandler] {$Script:EndScript++}

$Form_StateCorrection_Load = {$form.WindowState = $InitialFormWindowState}

$Form_Cleanup_FormClosed = {
	try {
		$form.remove_FormClosing($form_FormClosing)
		$form.remove_Load($FormEvent_Load)
		$form.remove_Load($Form_StateCorrection_Load)
		$form.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}

$Script:OptArray = @()
$End_Script = {
 	$Form.Close()
	$Script:EndScript = 1
	}
$BrowseButton_OnClick = {
	$FolderBrowser = New-Object System.Windows.Forms.FolderBrowserDialog -Property @{ShowNewFolderButton = $false}
	[void]$FolderBrowser.ShowDialog()
	$PSTPath = $FolderBrowser.SelectedPath
	$PSTPath = $PSTPath.ToLower()
	$textBox1.Text = $PSTPath
	}

$button4_OnClick = {
	$FolderBrowser2 = New-Object System.Windows.Forms.FolderBrowserDialog -Property @{ShowNewFolderButton = $false}
	[void]$FolderBrowser2.ShowDialog()
	$LogPath = $FolderBrowser2.SelectedPath
	$LogPath = $LogPath.ToLower()
	$textBox4.Text = $LogPath
	}
$OkButton_OnClick = {
	$Script:Source = $textbox1.text
	$Script:Target = $textbox2.text
	$Script:Key = $textbox3.text
	If ($checkBox1.Checked) {$Script:OptArray += "/S"}
	If ($checkBox3.Checked) {$Script:OptArray += "/Pattern:*.pst"}
	If ($checkBox2.Checked) {
	$LogPath = $textBox4.Text
		If (!$LogPath) {$Script:OptArray += "/V"}
		Else {$Script:OptArray += "/V:`"$LogPath\AzCopyVerbose.log`""}
	}
	$Script:EndScript = 2
	$Form.Close()
}
$OnLoadForm_StateCorrection = {
	$form.WindowState = $InitialFormWindowState
	}
$form.BackColor = 'White'
$form.Icon = [System.Convert]::FromBase64String('
AAABAAMAEBAAAAEAIABoBAAANgAAACAgAAABACAAqBAAAJ4EAAAwMAAAAQAgAKglAABGFQAAKAAA
ABAAAAAgAAAAAQAgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/QEQF
dHZtpH6AdP9/gHX/ra+g/7a4qP+ipJecAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACG
iXsHbG1kfnBybOR+gHT/eXtw/6aomf+1t6j/kZSL3JKUiGvf4c0EAAAAAAAAAAAAAAAAAAAAAAAA
AABkZlwEfoB0en+Bdd5vcGfBgoR4/3J0bf+XmY7/qqyd/4mKf8ieoJLhtLamZ01NSAEAAAAAAAAA
AAAAAAAAAAAAcXNpNXt9cu5ydGq+cHFnnHx+cP9mZ4//gYKc/5+hkP+Jin+VeXpwxJyekOefoJMs
AAAAAAAAAAAAAAAAAAAAAGprYxZ5e3C9eHpu+m9xZvF+gHD/VVau/29ws/+Zm4n/fH1y7JOViPij
pJe/i4yCFgAAAAAAAAAAAAAAAAAAAAAAAAAAZ2hgOHd4btx5e3D/d3hp/1RVoP9sbKn/nJ2M/56g
kv+ipJbfkpOIOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpamJKcHJosXt8cONkZq3/cXKx
/6Wnl+eeoJK/k5SITgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARkZKAQAAAAKDiY1P
lqa/85mov/Gbn59MXltPB1NTUQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABK
Y34Inr3fmLbP6v23z+n9tc3ojmNxgAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAATF5wW42guPSnus//q7vQ/56twPBcbHlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAHzZECh88TrplbXv/j5Od/46OmP91e4X/KUdZshw3RwkAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABEzRzMRN07pa4ef/5Wrwf+Tqb//b4ab/xI4TuUZRF0xAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZMD4zDzVL5ClNZP8uTmP/LlRr/ylKYP8RPFXtGkdiQwAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGDlMIQ80SeAMNEr/DDRM/xBCX/8QQV3/E0Zj
7xZCW2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB44RggVNkqUETVJ0g82TO8PN07x
DzlR/xNHZfUWPlVdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIjI8IRgzQzUV
O1F4FzhKXhUyQnkVOlCdFzZIUwAAAAAAAAAAAAAAAAAAAAD4HwAA+B8AAPAPAADgBwAA4AcAAPAP
AAD4HwAA/n8AAPw/AAD8PwAA+B8AAPgfAAD4HwAA+B8AAPgfAAD/3wAAKAAAACAAAABAAAAAAQAg
AAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABfYVppentw/36AdP9+gHT/enxx/3FyaP+pq5z/t7mp/7a4qP+3uaj/ra+g/nx9dGEA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAF1fWkJ3eW71foB0/36AdP+Bg3b/e31y/7O1pf+2uKj/trio
/7e5qf+oqpvwcXJqNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9gVxVaW1OBeH1+rHZ6cvl+gHT/foB0/36AdP9u
cGb/paaY/7e5qf+2uKj/t7mp/6GlmvGJjY2MfH1zWoiKfQkAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFiHsFfH5yf2lqYP1iZF/+cnRs
/n+BdP9+gHT/fH1y/2hqYP+bnI//trio/7S2pv+4uqn/l5qQ/3d5dP+QkoX0sLKjXgAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHluBn6AdHd/
gXX1f4F1/15fV8ZydGrkfoB0/4SGef9/gXX/aWpg/4+Qg/+ztaX/qauc/7S2pv+Zm47mYmRc3qKj
lf+3uanotLamVU9OSQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAB2eG1uf4F19YqMf/+GiHzUXl9aRnV3bN6DhXn/kpSG/3J0aP9hYmb/hIaC/6epmf+rrZ3/
mJqM/6KkltFmZ2FZhoh86bK0pP+2uKjnqqudSwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAbW9lPHx+cuJ+gHT/eHlu/29waG9YWVMqbG5k7IKEeP94em//dnhq/1dY
kf97fZv/lZeH/7Cyov+Ymoz/iIl+5Hd4ciVsbmWPgYN3/6SmmP+tr6DMl5mMIwAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoamKBhIV5/3R1a/9qa2L/Zmhfj11eWUN2d23t
foB0/2psYv+Vl4n/NTa+/2Rlsf+ipJH/jY+C/6ipm/+OkITka2xmLmNlXY5jZVv/fH1y/6+xof+P
kYVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFxcWCl6e3HUgoR4/3+B
df92eG35YWJa4XJ0afx4em7/dHZr/5ydl/8ZGtT/R0jA/7S2ov+KjH//pqiZ/5iajfdgYVnOh4h8
9amrnP+pq5z/oaOW2HN0bSwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAGdoYVl4em/0fH5y/3p8cP9naV//d3lu/3N1av+Cg3f/k5WQ/w8Oz/8yMsX/srSj/52fkf95
e3D/e3xx/2FiWf+Iin3/r7Gh/66wofaNj4VfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAQUFCBmNkXJF7fXH+gIJ2/3R2a/98fnP/cHJn/3d5bv+UlY//GhrM
/z4+wv+usJ//kZOG/56gkv+gopT/jI6B/6GjlP+vsaL/ioyBl0hIRwgAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDw6FWlqYq98fnL/dnhs/4SGev9z
dGr/YWJZ/4SFev83N7j/S0uy/5yej/+ChHj/p6ma/7Cyov+qrJ3/tLam/5OViLhTVFAbAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmNe
HWtsY7trbWP/gIJ2/3J0af92eG3/d3h8/ycnvP85Ob3/k5SQ/6utnf+kppf/ra+g/5iajP+anI+9
cHFoIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAWVpVMGNkXXRnaGB1ZGZdwYCBef3AwMv/ODrR/z9Bw/+9vcD/qKqe+5GT
h9GXmY2diIl/lXJzbDcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMTUgVe3t5mqessf6Ak6z/
eoqe/62yt/2enpqIYGFaFwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AABvfY00hZir56zE3f+uxt//hpam6HqDiy8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAeJa2J56+4bq+2PX9vdbx/73W8f/B2vb9u9TuqaG2zBoAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0PEgmBoMGsq8rr/7TL5f+vxt//scjh/6vC2v+/2PP/obbM
mgAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABuX0UBTltpRoemx+u10vH/v9j0/6zE3/+1
zef/vtfy/8Ha9v+mvNPgTVdgNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9seixFU2HbcYig
/5aitP+Tn63/oLfP/63B1/+Xoa//nqm3/4ybqf9OWmfKanmIHAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAL0JQchw2R/9JVF3/kXZ6/5aBhP96f4H/foCB/4RhZP+smJ3/YGVl/y9NX/s/VWVSAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAEdDQAcSMECiDjJI/0xmfP96gZH/iZOh/5aks/+UorD/hYuZ/4uToP9gc4P/
EjpR/xU2SKY+OzkLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETZMJw84UOAON07/TWqD/4ygtv+UqL3/rcTd/6e+
1v+Rpbr/k6a7/1Noef8LL0P/E0Ba2yNRbCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQNEl4DzZN/wwySP9CY3z/
scvo/8Xe+f9rf5L/ZHuO/8Ha9v+40Or/RV1v/wosQP8TO1PwGEhjdgsvRAUAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERUXCR0s
NGoUMUHfDztU/xM6Uf9Zc4n/boec/xkyQf8YPFL/aYOY/1tzh/8RNEj/DTRK/xpKZt0jO0lTGicu
GQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABUS0YEIjE6IRE6Uc8ONUv/DTNJ/w0zSf8NMkf/Cys9/xFCX/8POVL/DC9E/w00Sv8P
OFD/FElo9xlXe1prGwACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYMUAwEDpS7QwwRP8NM0j/EDtV/xA9Vv8POFD/EkNg
/xdXfP8PO1T/DjdO/xA9V/8RPVb5E0VhwBBDYBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACM1PyATOlDeCyw//w0zSP8P
OVL/DC5B/w42Tv8ON07/FVFz/xFBXf8WU3b/E0hn/xlVd8kbO06MEzJESwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYDIY
AxU4S54QNkz5EjRI5g84UP8LKjz/DzlR/w0zSf8ONkz/DjZO/xNHZv8VUXP/FExt9hlPbmcjKy80
IyIiAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAGTREShg7T7seMj50ETZM7Q41TP8VPVTKETlQ6Q43T/8ML0P/Cic4/xFB
Xf8USWj/EThPsRchJwxSRT4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlMzwPIjA4YDYuKwsVMEBSEztS2RRBW4MaM0JI
FThLshg0RcUUM0SxEjZL2BM/WfEXNEaWDxkeEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArKioSIiMjBAAA
AAAdM0AqHDhIYis8Rg8yMjMJMTU3F0pGRAcnN0EfHThHXho3R3sdLTcZAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD/4Af//+AH//+AA///gAH//wAA//4gBH/8YAQ/+CAEP/wAAD/+AAB/
/gAAf/8AAP//gAH///AD///4H////D////gf///wD///8A///+AH///gB///wAP//8AD///AA///
wAP//8AD///AAf//wAH//8AD///oAf///IH//////ygAAAAwAAAAYAAAAAEAIAAAAAAAACQAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABLTEk7bm9m83+Bdf9+gHT/foB0/36AdP99f3P/cHJn/2doX/+hopT/
t7mp/7a4qP+2uKj/trio/7a4qP+3uan/l5mM7lZWUzQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMTEwaaWpi2H6AdP9+gHT/foB0
/36AdP+ChHf/dnht/3h5b/+ztaX/trio/7a4qP+2uKj/trio/7a4qP+2uKj/jI2CzDw7PRIAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA5OUEGYmRctX1/c/9+gHT/foB0/36AdP+Ehnn/e31x/3d5bv+2uKj/trio/7a4qP+2uKj/trio
/7a4qP+ztaX/goN5pAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAVVdOJlhZU2aRlJdvbnZ3zHt9cv9+gHT/foB0/36AdP9+gHT/enxx/2ps
Yv+rrZ3/trio/7a4qP+2uKj/trio/7a4qP+vsqL/f4WDp6KjpER5enIzjY+CCgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABvcWcJZmherFJUTP90dXL9cXZ5/nl7b/9+
gHT/foB0/36AdP9+gHT/fH5y/1ZXT/+Rk4b/t7mp/7a4qP+2uKj/trio/7e5qf+qrZ//g4qN9Y2O
ifR2eG3wjY+CdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKEeAV+gHR0
f4F19mhqYP9YWlL/Y2Rg/Xh6b/9+gHT/foB0/36AdP99f3P/cnRp/2JjWv+Ulon/t7mp/7O1pf+y
tKT/trio/7e5qf+nqZr/cnRw/3N0a/+LjYH/srSl47K0pUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAfH5yBX+BdHN+gHT0foB0/36AdP9cXlX2WltVyHl7cPx+gHT/foB0/3+Bdf+Agnb/
d3lu/2doX/+Fhnv/sbOj/7S2pv+nqZr/s7Wl/7e5qf+pq5z5YmNd3l5fV/2ipJb/uLqq/7a4qNy1
t6dCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqa2IFfH5yc36AdPR9f3P/iYt+/4eIfPteX1h+Y2Ve
dHp8cf9+gHT/gYN3/5aYiv+Ji37/Z2lf/1tcVP+Gh3z/m52P/7i6qv+srp//l5mM/7O1pf+tr6D6
d3hxd2FiW7qPkYT/srSk/7a4qP+1t6fcrK6fQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtbmRhfX9z9H6A
dP+Fh3r/mJqM/3V3br1UVFYRZGVehXt9cf98fnL/l5mL/5KUhv9sbmP/amtg/1hZbf+Gh4r/i4x/
/66wof+3uan/kpSH/5CShf+qrJ7/gIF5Y15eWy5yc2rjm52O/7e5qf+2uKj/s7Wl15qbji8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAGxtYyd3eW3PgoR4/4qMf/+OkIP/e31y82RlYEgAAAAAYmRcn29xZv97fHH/j5GE/3d5
bf9dXlb/jpCB/z09i/91dpf/np+P/4+RhP+2uKj/sbOk/4GCd/+QkoX/gIF4hAAAAABpamR6enxx
/6GjlP+ztaX/tLam/6OklqaOkIMLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANDQ2B21vZax/gXX/gYN3/2RlXP9TVEz/XV5X4GlpZiEA
AAAAZGZeoW1vZf+Bg3f/f4F1/2NkW/96fHD/m52S/x4etf9YWaf/tbej/4GDd/+dnpD/uLqq/6Ol
l/9/gHX/goN6lgAAAABubms2W1xU7lNUTP92eG3/paeZ/7W3p/qUlYl+AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUlJUCmVnX7qBg3f/
j5GE/2psYv98fnL/bG5k+mFiW4lSUlEcaWtjo4CCdv9/gXX/dnht/2FiWf+doI//iYqa/wcH4P87
PLX/tLaj/5+hk/95em//l5mL/6utnv+bnY//dndvgTc2PQhdXlh4Zmhf+2ttY/9mZ17/oaOV/7W3
p/+Ji4CtAQANBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAFhZVURzdWvnjI6B/4GDd/+Bg3f/f4F1/3d4bfxeX1jWW1xU7Xt9cf9/gXX/
aWth/3N0af+vsZ7/bG6b/wAA8v8kJMf/qauf/7a4p/+ChHj/iIp+/7O1pf+tr6D/ZWZe0mJjXLh6
fHH4nJ6Q/6qsnf+jpZb/rK6e/5+gk+tnaGJJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABlZmB2eHpv/H6AdP98fnL/dXds
/3Z4bf9vcGb/XV9W/31/c/99f3P/YmRa/4WHe/+ztaL/VVWK/wAA9f8TE9j/m5yc/7m7qv+lp5j/
hIZ6/6anmf+jpZb/Z2hf/2FjWv+ChHj/qqyd/7a4qP+4uqr/rrCh/oWGfoAAAAABAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AABUVVMRZ2hgtnx+cv99f3P/f4B1/3p7cP9oaWD/Z2hf/3+Bdf98fnL/YWNZ/4+RhP+xs6D/Q0N6
/wAA9f8KCtv/iIqR/7m7qf+ys6T/cHFn/2VmXf9vcGf/Z2hf/11eVv98fXL/nZ+R/6+xof+0tqb/
kZOIvmVlYxUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT1BNNmdoYN+Agnb/gYN3/4CCdv9xc2n/cXNo/3+B
df99f3P/YWJZ/4yNgf+ur53/VVaE/wEB8f8XF9X/jo+Q/7i6qf+jpZb/jI2B/6aomf+kppf/iYp+
/36Adf+LjYH/trio/7a4qP+UlYnjYWJdPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEdIRFpr
bWPwfoB0/3+Bdf98fnL/fH1y/4CCdv93eW7/UFFK/2tsYv+gopP/bm6I/wgI5f8pKdD/mpuX/7O1
pP92d23/hYZ6/7i6qv+2uKj/qKqb/6+xof+wsqL/t7mp/52ekfdfYFpoAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAANVVlB0dHZr93+Bdf9wcmf/eHpu/42Pgf+AgXb/ZWdd/1hZUf9/
gHX/fn6D/x8fzf8rK7v/i4yG/5eYi/9+f3T/kJGF/7Cyo/+ztaX/o6WX/6yun/+4uqr/p6mb+G5v
Z4MsKzAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVVVgHZmdgeHJ0avhhY1n/
fH5y/4mLfv94em//bnBl/3p8cP90dWv/cnKG/xoas/8tLbH/m5ul/5iZjf+0tqb/n6GT/6mqnP+w
sqL/oKGT/46Qg/+rrZ74hYZ7hB0dHQkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAeXl6CVtcVqNlZ176c3Vr7XR2a/RmZ17/dHZr/3h6b/+goJv/SUmw/wAA+v8BAfH/
WFib/5iZkP+ur6D/qKqb/56gkv+tr6D/q6ye/46Qg/9/gHekVVVTCQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFpaVx5ZWldDVVZSL1lZVUNXWFKRbnBm
8ICBe//u7u3/pqbI/yIkxf8qLbX/sLC//+Tk4/+io5r/nZ+S8np7criCg3x3gYJ7aG5vZ2lqa2Yt
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABNTE8EUlJOWn19e+HR0dL/pLC7/4OcuP9zhZn/nKex/9jZ2/+goJ7Ha2xm
R1NSVAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG5sa19la3H0cIOX/4OZ
r/+Dl6v/doaY/290ePaQj41SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAHKIoTGHm7Hcts7n/8Td+f/F3/v/tc3n/4CQoOJxfosqAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfpy8Pp2+4c3A2/n/xN76/8DZ9P/A2fT/xN76/8Te+v66
0+25pbvRJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABshqE6ja/U3qzL7f+50ev/
ssrj/67E3f+uxd7/tc3n/7vT7v/D3Pj/tc3nxIKTpSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAhviaWymb3j/7jU8v+zyuP/r8bg/7PL5P+0zOb/rsTd/5uvxv+/2fT/wNr1/4CRopoAAAAC
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAACwxNyp4lbPlocTp/8Db+P/F3/v/utTv/6S60v+sw9v/wNn0
/8Hb9//D3fn/xN76/5CkuNIQEhMWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVmBpOUpVYMCDo8T8nLrb/7HH
3/+zyOD/qMTj/67I5f+81e//utLs/7PJ4P+zyOD/utHr/6C1zPhIUlqnWWRsJQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABy
fogKWGd2qjdEUf9uhZ7/c4KR/4+XpP+Kk53/c3yG/6vE3v+3zeb/gIiQ/4ySnv+Smqb/ho6V/46c
q/9AS1b/YXGBg9PJtgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABETlcyNUtb7hUyQ/8sMjT/m6i3/6l5fv/BnaT/hYmN/4eQmf+M
k5r/goKH/51ka//QrrP/qLS+/0RANv8mRlr/VWl70j5ESRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfLzhcDSw++A8xRf86SFT/
YGNp/1cyMP90Xl//d3p8/21rZv90cGf/bmpq/1cxMP+HcW//dnh6/19ma/8ZRV//Fz1U5hopMjqS
YUQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AFE6LQUYM0OJDTFF/Q0zSf8/YXv/hKC9/5OnvP+ht83/mq7E/67F3f+nvNT/oLTK/6G2zP+Xqr7/
nrHH/0lkeP8ONUv/DzdO/x06SqZLSkoPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABUwQBoQNkvVDjVL/w88Vv8wTWP/coac/4OUpv93hpf/jJ6y
/7rS7P+yyeL/g5Sm/3mImv+Elaj/f4+h/yo+S/8LMEX/DzhQ/xQ6UMwxO0EeAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA43T2UQPVf7DztU/wsu
Q/8+W3L/m7jX/6K3zv+0y+X/xt/8/4+kuf+LoLb/xN35/67E3f+judD/tczl/z9VZf8JKTz/DjdP
/xZQcu0cZZBSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAABBUfDQ80Sb8QNkz/DC9D/w02Tf8aPFL/g6G//8Xf/f/G4P3/tMzl/zBBTv8oQFD/qsLb/8fh
/f/I4v7/jaK4/xUuPf8LLUD/DTBF/xQ1R+gXRF26EkRgLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADBgfMR4wOpwWKTTiDjVL/xFAW/8OOlP/LUth/5Kpwv+n
v9f/Wm+B/wohL/8LLUD/SmZ6/6S60v+VqsD/LUha/wsuQv8NMEX/EkZk/x5EWtAnNDtPFCg0XhME
AAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKioqKzc0MygYNUaw
ED1W/w43T/8NMEX/DTNJ/xkzQ/8fQFX/Cyg5/womN/8QPFX/E0Zj/xw0Q/8ZNUf/DDBF/w85Uf8M
L0P/DzlR/x5fheguao0wMi4rHDMzNAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAnJWQBA0gKxcON07OED1X/wwtQP8POE//DTJH/w45Uv8NNEv/DTBF/wsrPf8QO1T/
FVJ1/wwxRv8MMEX/DjZN/w0xRf8QPFb/EUBc/xJHZf8WVHiVHEdfBQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABovOz0QOlHzDzlR/wwtQP8NMkf/DzhQ
/xA9V/8QO1T/EUFc/w0zSP8QPFb/GFyE/xVRdP8PN0//DjdO/w40S/8ONUz/DzhQ/xFBXP8TSmrs
FExtOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIy
PDkSOVDyDzhQ/wspO/8ML0P/DztU/w87VP8ONUz/ET9a/w85Uf8POFD/FVBy/xpijP8ON07/FEtr
/w43Tv8USmr/FExt/xU0RcUWO1DbET9ZmwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAADU6PRoVOEzVDztU/wkiMP8NMkf/EDtV/w85Uv8KJTX/DC5C/w85
Uf8MLkL/ED9Z/xdWe/8POVH/FU5w/xpkjv8PO1T/FlR3/x1qlq0rPklDFzNDsg0oOCgAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZNEOMEDtU/w0vQ/0S
MkXzEDtV/w85Uv8JIC7/DjRK/w86U/8NMkj/DC0//xA+WP8RQFv/DjRK/xhagf8YW4L/DzpS/xZW
evgXWH5eLTU5OR0oLkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAiMTo6EjlQ7xU/V98dMDqPEDhP/RA7Vf8JIjD/EkRg/g80SvwQPVf/DjVL/wsrPf8N
MEX/Cyg6/w42TP8VT3D/F1Z7/xJDYP8TSGfKDyUzFjg2NhgrKysDAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+LiUIFzVHshs7Ta8xLy0sHDI+uQ86U/oLLUD/
Fkln9BoyP5URN03lED1X/xA8Vv8NM0n/Cig5/wgfLP8NM0j/FE5v/xRGYv4SNUrvCyg5QgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDA6
USQyO4IAAAAAHiAiExQwQZEROE75E0dl8RZAWTgcLjg/GDdJvRI4TvUUM0X5FjhM3xE0R/APNEr9
ED5Y/xNEYPcdNkWgEyIqWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAANzk6DiMmJ0QTEhIDAAAAADUzMgoeNEBgFDhNyRQ7UoYdJy0EQ0ND
DyMzPUIiLzZvNzs9MCY2PzQcNEFhGzhIpBQ5Td8TOlG2FCo3NwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADk5OQgrKysCAAAAAAAA
AAAAAAAAKzM3GSg4QlE3QEUWAAAAAAAAAACrq6sBsrKyAQAAAAAAAAAAYlNJBC44PSYkOERsHTE8
XzMyMgcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA
//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP/4AAA//wAA//gAAB//AAD/8AAAD/8AAP/hgAEH
/wAA/8EAAYP/AAD/gwAAwf8AAP8DAADB/wAA/wEAAMD/AAD/gAAAAf8AAP/AAAAB/wAA/8AAAAP/
AAD/4AAAB/8AAP/wAAAP/wAA//gAAA//AAD//AAAH/8AAP/8AAA//wAA///AA///AAD///AP//8A
AP//+B///wAA///4H///AAD///AP//8AAP//4Af//wAA///AA///AAD//8AD//8AAP//gAH//wAA
//8AAP//AAD//wAA//8AAP//AAD//wAA//4AAH//AAD//gAAf/8AAP/+AAB//wAA//wAAD//AAD/
/AAAf/8AAP/+AAB//wAA//4AAD//AAD//gAAP/8AAP/+AAAf/wAA//4AAF//AAD//gAAf/8AAP//
AAA//wAA//8gAD//AAD//7GAP/8AAP///P4//wAA////////AAA=')
$form.Size = '616, 450'
$form.Name = "form"
$form.StartPosition = 'CenterScreen'
$form.Text = "Get-AZCopyGUI.ps1"
$form.add_FormClosing($form_FormClosing)
$form.add_Load($FormEvent_Load)
$form.KeyPreview = $True
$form.Add_KeyDown({if ($_.KeyCode -eq "Enter"){
	$Script:Source = $textbox1.text
	$Script:Target = $textbox2.text
	$Script:Key = $textbox3.text
	$Script:EndScript = 2
	$Form.Close()
	}})
$form.Add_KeyDown({if ($_.KeyCode -eq "Escape")
    {$form.Close()
	}})
$form.MainMenuStrip = $menu
$form.Controls.Add($menu)
[void]$menu.Items.Add($fileToolStripMenuItem)
[void]$menu.Items.Add($editToolStripMenuItem)
[void]$menu.Items.Add($helpToolStripMenuItem)
$menu.Location = '0, 0'
$menu.Name = "Menu"
$menu.Size = '344, 24'
$menu.TabIndex = 0
$menu.Text = "Menu"
$menu.BackColor = "White"
[void]$fileToolStripMenuItem.DropDownItems.Add($exitToolStripMenuItem)
$fileToolStripMenuItem.Name = "fileToolStripMenuItem"
$fileToolStripMenuItem.Size = '37, 20'
$fileToolStripMenuItem.Text = "File"
$fileToolStripMenuItem.BackColor = "White"
$exitToolStripMenuItem.Name = "exitToolStripMenuItem"
$exitToolStripMenuItem.Size = '152, 22'
$exitToolStripMenuItem.Text = "Exit"
$exitToolStripMenuItem.BackColor = "White"
$exitToolStripMenuItem.add_MouseEnter($menu_MouseEnter)
$exitToolStripMenuItem.add_MouseLeave($menu_MouseLeave)
$exitToolStripMenuItem.add_Click($End_Script)
[void]$editToolStripMenuItem.DropDownItems.Add($copyToolStripMenuItem)
[void]$editToolStripMenuItem.DropDownItems.Add($pasteToolStripMenuItem)
$editToolStripMenuItem.Name = "editToolStripMenuItem"
$editToolStripMenuItem.Size = '39, 20'
$editToolStripMenuItem.Text = "Edit"
$copyToolStripMenuItem.Name = "copyToolStripMenuItem"
$copyToolStripMenuItem.ShortcutKeys = 'Ctrl+C'
$copyToolStripMenuItem.Size = '152, 22'
$copyToolStripMenuItem.Text = "Copy"
$copyToolStripMenuItem.add_Click({
	$ActiveTextbox = $form.ActiveControl
	$ActiveTextbox.Copy()
	})
$pasteToolStripMenuItem.Name = "pasteToolStripMenuItem"
$pasteToolStripMenuItem.ShortcutKeys = 'Ctrl+V'
$pasteToolStripMenuItem.Size = '152, 22'
$pasteToolStripMenuItem.Text = "Paste"
$pasteToolStripMenuItem.add_Click({
	$ActiveTextbox = $form.ActiveControl
	$ActiveTextbox.Paste()
	})
[void]$helpToolStripMenuItem.DropDownItems.Add($aboutToolStripMenuItem)
[void]$helpToolStripMenuItem.DropDownItems.Add($helpMenuItem)
$helpToolStripMenuItem.Name = "helpToolStripMenuItem"
$helpToolStripMenuItem.Size = '44, 20'
$helpToolStripMenuItem.Text = "Help"
[void]$aboutToolStripMenuItem.DropDownItems.Add($versionMenuItem)
$aboutToolStripMenuItem.Name = "aboutToolStripMenuItem"
$aboutToolStripMenuItem.Size = '152, 22'
$aboutToolStripMenuItem.Text = "About"
$versionMenuItem.Name = "ToolStripMenuItem"
$versionMenuItem.Size = '164, 22'
$versionMenuItem.Text = "Script Version 1.1"
$versionMenuItem.add_Click({
	Start-Process -FilePath http://cgoo.se/1G313oX
	})
$helpMenuItem.Name = "getHelpToolStripMenuItem"
$helpMenuItem.Size = '152, 22'
$helpMenuItem.Text = "Get Help"
$helpMenuItem.add_Click({
	Start-Process -FilePath http://cgoo.se/1Qnxtfg
	})
$CancelButton.Location = '332, 349'
$CancelButton.Name = "CancelButton"
$CancelButton.Size = '75, 25'
$CancelButton.TabIndex = 7
$CancelButton.Text = "Cancel"
$CancelButton.FlatStyle = 'System'
$CancelButton.ForeColor = 'Black'
$CancelButton.add_Click($End_Script)
$form.Controls.Add($CancelButton)
$OkButton.Location = '192, 349'
$OkButton.Name = "OkButton"
$OkButton.Size = '75, 25'
$OkButton.TabIndex = 6
$OkButton.Text = "Ok"
$OkButton.FlatStyle = 'System'
$OkButton.ForeColor = 'Black'
$OkButton.add_Click($OkButton_OnClick)
$form.Controls.Add($OkButton)
$groupBox1.Location = '12, 246'
$groupBox1.Name = "groupBox1"
$groupBox1.Size = '576, 83'
$groupBox1.TabStop = $False
$groupBox1.Text = "Options:"
$form.Controls.Add($groupBox1)
$checkBox2.Location = '482, 15'
$checkBox2.Name = "checkBox2"
$checkBox2.Size = '88, 24'
$checkBox2.TabIndex = 5
$checkBox2.Text = "Verbose (/V)"
$checkBox2.UseVisualStyleBackColor = $True
$groupBox1.Controls.Add($checkBox2)
$checkBox1.Location = '97, 15'
$checkBox1.Name = "checkBox1"
$checkBox1.Size = '104, 24'
$checkBox1.TabIndex = 4
$checkBox1.Text = "Recursive (/S)"
$checkBox1.UseVisualStyleBackColor = $True
$groupBox1.Controls.Add($checkBox1)
$checkBox3.Location = '270, 15'
$checkBox3.Name = "checkBox3"
$checkBox3.Size = '130, 24'
$checkBox3.TabIndex = 6
$checkBox3.Text = "*.PST Only (/Pattern)"
$checkBox3.UseVisualStyleBackColor = $True
$groupBox1.Controls.Add($checkBox3)
$label5.Location = '1, 46'
$label5.Name = "label5"
$label5.Size = '77, 23'
$label5.Text = "Log Location:"
$label5.TextAlign = 32
$groupBox1.Controls.Add($label5)
$button4.Location = '501, 47'
$button4.Name = "button4"
$button4.Size = '75, 23'
$button4.TabIndex = 4
$button4.Text = "Browse"
$button4.FlatStyle = 'System'
$button4.ForeColor = 'Black'
$button4.add_Click($button4_OnClick)
$groupBox1.Controls.Add($button4)
$textBox4.Location = '97, 50'
$textBox4.Name = "textBox4"
$textBox4.Size = '398, 20'
$textBox4.TabIndex = 3
$groupBox1.Controls.Add($textBox4)
$label3.Location = '13, 202'
$label3.Name = "label3"
$label3.Size = '78, 23'
$label3.Text = "Storage Key:"
$label3.TextAlign = 16
$form.Controls.Add($label3)
$textBox3.Location = '109, 166'
$textBox3.Multiline = $True
$textBox3.Name = "textBox3"
$textBox3.Text = "<Paste here>"
$textBox3.add_Click({$textBox3.Text = ""})
$textBox3.Size = '479, 60'
$textBox3.TabIndex = 3
$form.Controls.Add($textBox3)
$label2.Location = '13, 126'
$label2.Name = "label2"
$label2.Size = '90, 23'
$label2.Text = "Destination URL:"
$label2.TextAlign = 16
$form.Controls.Add($label2)
$textBox2.Location = '109, 126'
$textBox2.Name = "textBox2"
$textBox2.Text = "<Paste here>"
$textBox2.add_Click({$textBox2.Text = ""})
$textBox2.Size = '479, 20'
$textBox2.TabIndex = 2
$form.Controls.Add($textBox2)
$BrowseButton.Location = '513, 83'
$BrowseButton.Name = "BrowseButton"
$BrowseButton.Size = '75, 25'
$BrowseButton.TabIndex = 0
$BrowseButton.Text = "Browse"
$BrowseButton.FlatStyle = 'System'
$BrowseButton.ForeColor = 'Black'
$BrowseButton.add_Click($BrowseButton_OnClick)
$form.Controls.Add($BrowseButton)
$textBox1.Location = '109, 86'
$textBox1.Name = "textBox1"
$textBox1.Text = "<Type UNC path or Browse>"
$textBox1.add_Click({$textBox1.Text = ""})
$textBox1.Size = '398, 20'
$textBox1.TabIndex = 1
$form.Controls.Add($textBox1)
$label1.Location = '12, 86'
$label1.Name = "label1"
$label1.Size = '78, 23'
$label1.Text = "PST Location:"
$label1.TextAlign = 16
$form.Controls.Add($label1)
$label4.Location = '176, 39'
$label4.Name = "label4"
$label4.Size = '248, 23'
$label4.TabIndex = 10
$label4.Text = "AZCopy GUI for PST Import"
$label4.Font = "Segoe UI, 9.75pt, style=Bold"
$label4.TextAlign = 'MiddleCenter'
$form.Controls.Add($label4)
$form.ResumeLayout()
$InitialFormWindowState = $form.WindowState
$form.add_Load($Form_StateCorrection_Load)
$form.add_FormClosed($Form_Cleanup_FormClosed)
$form.add_Shown({$form.Activate()})
return $form.ShowDialog()
} #End Function
Write-Host "Checking OS architecture..." -ForegroundColor Green
If ([System.Environment]::Is64BitOperatingSystem -eq "True"){
	$Programfiles = [Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
	}
Else {$Programfiles = [Environment]::GetEnvironmentVariable("ProgramFiles")
	}
Write-Host "Checking AZCopy..." -ForegroundColor Green
$AZCopyPresent = Test-Path "$ProgramFiles\Microsoft SDKs\Azure\AZCopy\AZCopy.exe"
If ($AZCopyPresent -ne "True") {
	Write-Host "Unable to find AZCopy.exe in the default path.." -ForegroundColor Red
	$Title = "Download it now?"
	$Message = "Would you like to download a copy of AZCopy now?"
	$Yes = New-Object System.Management.Automation.Host.ChoiceDescription "&Yes", "Download a copy of AZCopy from the Microsoft website now"
	$No = New-Object System.Management.Automation.Host.ChoiceDescription "&No", "Exit this script"
	$Options = [System.Management.Automation.Host.ChoiceDescription[]]($Yes, $No)
	$Result = $Host.UI.PromptForChoice($Title, $Message, $Options, 0)
	Switch ($Result){
		0 {Start-Process -FilePath http://aka.ms/downloadazcopy; Exit}
		1 {Exit}
		}
	}
Write-Host "Launching GUI..." -ForegroundColor Green
Call-GUI | Out-Null
If ($EndScript -eq 1) {
	Write-Host "Script cancelled" -ForegroundColor Red
	Exit
	}

If (!$Target -or !$Source -or !$Key) {
	Write-Host "Please complete all fields and try again.." -ForegroundColor Red
	Sleep -Seconds 2
	Call-Gui
	}

$TargetSuffix = $Source -replace "\\","/" -replace ".\s+"
If ($Target.EndsWith("/") -eq "True") {
	$Target = $Target.Substring(0,$Target.Length-1)
	}
If ($TargetSuffix.StartsWith("//") -eq "True") {
	$TargetSuffix = $TargetSuffix.Substring(1)
	}
Else {
	$TargetSuffix = $TargetSuffix.Substring(2)
	}
$Options = [system.string]::Join(" ",$OptArray)
Write-Host "Running AZCopy..." -ForegroundColor Green
Start-Process -FilePath "$ProgramFiles\Microsoft SDKs\Azure\AZCopy\AZCopy.exe" -ArgumentList "/Source:`"$Source`" /Dest:$Target$TargetSuffix /Destkey:$Key $Options" -PassThru
